package com.petproject.musicguessr.model;

public enum EventType {
    SEARCH_REQUEST_TARGET,
    SEARCH_REQUEST_BROADCAST,
    SEARCH_RESPONSE,

    SONG_REQUEST_TARGET,
    SONG_REQUEST_BROADCAST,
    SONG_RESPONSE,

    WORD_REQUEST,
    WORD_REQUEST_TARGET,
    WORD_REQUEST_BROADCAST,
    WORD_RESPONSE,

    SHOW_INVITE_CODE_REQUEST,
    SHOW_INVITE_CODE_REQUEST_TARGET,
    SHOW_INVITE_CODE_REQUEST_BROADCAST,
    SHOW_INVITE_CODE_RESPONSE,

    NONE,
    ERROR,
}
