package com.petproject.musicguessr.model;

public enum EventType {
    SEARCH_REQUEST_TARGET("SEARCH_REQUEST_TARGET"),
    SEARCH_REQUEST_BROADCAST("SEARCH_REQUEST_BROADCAST"),
    SEARCH_RESPONSE("SEARCH_RESPONSE"),

    SONG_REQUEST_TARGET("SONG_REQUEST_TARGET"),
    SONG_REQUEST_BROADCAST("SONG_REQUEST_BROADCAST"),
    SONG_RESPONSE("SONG_RESPONSE"),

    WORD_REQUEST("WORD_REQUEST"),
    WORD_REQUEST_TARGET("WORD_REQUEST_TARGET"),
    WORD_REQUEST_BROADCAST("WORD_REQUEST_BROADCAST"),
    WORD_RESPONSE("WORD_RESPONSE"),

    SHOW_INVITE_CODE_REQUEST("SHOW_INVITE_CODE_REQUEST"),
    SHOW_INVITE_CODE_REQUEST_TARGET("SHOW_INVITE_CODE_REQUEST_TARGET"),
    SHOW_INVITE_CODE_REQUEST_BROADCAST("SHOW_INVITE_CODE_REQUEST_BROADCAST"),
    SHOW_INVITE_CODE_RESPONSE("SHOW_INVITE_CODE_RESPONSE"),

    NONE("NONE"),
    ERROR("ERROR");

    private final String text;

    EventType(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }
}
